# Generated by Django 5.0.7 on 2024-07-21 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('soltero', 'Soltero'), ('casado', 'Casado'), ('divorciado', 'Divorciado'), ('viudo', 'Viudo')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='residencia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
