# Generated by Django 5.0.7 on 2024-10-14 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0009_producto_stock'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Marca',
            new_name='Categoria',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='marca',
            new_name='categoria',
        ),
    ]
